obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[1,1], [1,-1],[-1,-1],[-1,1]]
#robot_radius: ir_of_robot
inflation_radius: 0.1

observation_sources:  point_cloud_sensor

#laser_scan_sensor: {sensor_frame: base_frame, data_type: LaserScan, topic: LaserScan, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: body, data_type: PointCloud2, topic: point_cloud_position_of_cars, marking: true, clearing: true}