local_costmap:
    global_frame: world
    robot_base_frame: body
    update_frequency: 1.0
    publish_frequency: 1.0
   
    rolling_window: true
    width: 40
    height: 40
    resolution: 2.0
    
    transform_tolerance: 4.0 
    
    inflate_around_unknown: true 

    plugins: 
        - {name: static_layer,            type: "costmap_2d::StaticLayer"}
        - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
        - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}

    static_layer:
        enabled:              true
        map_topic:            "projected_map_2"


    inflation_layer:
        enabled:              true
        cost_scaling_factor:  500  
        inflation_radius:     30

    obstacle_layer:
        enabled: false
     #   observation_sources: laser_scan_sensor
      #  footprint_clearing_enabled: true
       # laser_scan_sensor: {data_type: LaserScan, sensor_frame: base_link, clearing: true, marking: true, topic: /LaserScan}
          
