local_costmap:
    global_frame: world
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 2.0
   
    rolling_window: true
    width: 50
    height: 50
    resolution: 1.0

    plugins: 
        - {name: static_layer,            type: "costmap_2d::StaticLayer"}
        - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
        - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}

    static_layer:
        enabled:              true
        map_topic:            "projected_map_2"


    inflation_layer:
        enabled:              false
        cost_scaling_factor:  5  
        inflation_radius:     1.0

    obstacle_layer:
        enabled: false
     #   observation_sources: laser_scan_sensor
      #  footprint_clearing_enabled: true
       # laser_scan_sensor: {data_type: LaserScan, sensor_frame: base_link, clearing: true, marking: true, topic: /LaserScan}
          